### ISSUE TITLE
Typo for BMUN Conference Description

### ISSUE THREAD

**Issue by Gravitonic** [jeffreymeng/montavistamun#52]
On the conferences page:

> Our fifth conference of the year, Berkeley Model United Nations Conference, is meant for veterans and varsity members. BMUN is tough, but we’re sure that you will have such a great time meeting members from all over the world. It’s also a great way to analyze and practice your speech skills in a group of more experienced delegates. BMUN is our second overnight conference, located in nearby Berkeley, California, including a 2-night **_stay and stay_** at a hotel in Berkeley.

**Comment by jeffreymeng** [comment]
fixed in 92b24d21b3548e1a07668a1282df40ea20443c2c
